-- ════════════════════════════════════════════════════════════════════
-- Fluxe BPO — Migração: Esteiras → tarefa_modelos (sistema único)
-- Execute no SQL Editor do Supabase
-- ════════════════════════════════════════════════════════════════════
-- Gerado automaticamente a partir do conteúdo real de EsteirasPage.jsx
-- (90 tarefas, todas as 9 esteiras) -- nada foi digitado à mão, pra não
-- correr risco de errar um checklist na transcrição.
--
-- Cada tarefa de Esteira vira um tarefa_modelos com recorrencia='unica'
-- (executa uma vez quando vinculada a um cliente, sem ciclo recorrente).
-- As 5 tarefas de 'configurar empresa no ERP X' ganham software_alvo,
-- pra nunca mais gerar as 5 juntas pro mesmo cliente.
--
-- Roda pra TODAS as empresas existentes automaticamente (sem precisar
-- trocar ID manualmente) e é seguro rodar mais de uma vez -- usa o mesmo
-- índice único de dedup_tarefa_modelos.sql pra não duplicar.
-- ════════════════════════════════════════════════════════════════════

ALTER TABLE tarefa_modelos ADD COLUMN IF NOT EXISTS software_alvo TEXT;
ALTER TABLE tarefa_modelos ADD COLUMN IF NOT EXISTS segmento_alvo TEXT;
ALTER TABLE tarefa_modelos ADD COLUMN IF NOT EXISTS origem TEXT; -- 'esteira' ou NULL (modelo tradicional)

-- Pré-requisito: supabase/dedup_tarefa_modelos.sql já deve ter sido rodado
-- (cria o índice único (empresa_id, titulo, categoria) WHERE ativo=true)

INSERT INTO tarefa_modelos
  (empresa_id, titulo, descricao, categoria, etapa, prioridade, recorrencia, checklist_items, software_alvo, segmento_alvo, origem, ativo)
SELECT
  e.id, d.titulo, d.descricao, d.categoria, d.etapa, 'media', 'unica', d.checklist::jsonb, d.software, NULL, 'esteira', true
FROM empresas e
CROSS JOIN (VALUES
  ('Identificar empresa-alvo e pesquisar porte e segmento', 'Jornada Comercial › Prospecção & Diagnóstico', 'Relacionamento', 'comercial', '["Verificar faturamento estimado","Identificar segmento de atuação","Pesquisar concorrentes que atendem"]', NULL),
  ('Primeiro contato — WhatsApp ou LinkedIn', 'Jornada Comercial › Prospecção & Diagnóstico', 'Relacionamento', 'comercial', '["Preparar mensagem de abordagem","Enviar mensagem","Registrar resposta"]', NULL),
  ('Agendar reunião de diagnóstico', 'Jornada Comercial › Prospecção & Diagnóstico', 'Relacionamento', 'comercial', '["Confirmar data e horário","Enviar convite","Preparar pauta da reunião"]', NULL),
  ('Levantar processos financeiros atuais', 'Jornada Comercial › Prospecção & Diagnóstico', 'Estratégico', 'comercial', '["Quem faz o financeiro hoje?","Qual sistema usa?","Quais dores principais?","Volume de NFs por mês","Volume de pagamentos por mês"]', NULL),
  ('Elaborar proposta personalizada', 'Jornada Comercial › Proposta & Fechamento', 'Estratégico', 'comercial', '["Definir escopo dos serviços","Calcular precificação","Preparar apresentação"]', NULL),
  ('Enviar proposta ao decisor', 'Jornada Comercial › Proposta & Fechamento', 'Relacionamento', 'comercial', '["Enviar por WhatsApp","Enviar por e-mail","Agendar follow-up em 48h"]', NULL),
  ('Follow-up da proposta', 'Jornada Comercial › Proposta & Fechamento', 'Relacionamento', 'comercial', '["Ligar para o decisor","Tratar objeções","Ajustar escopo se necessário"]', NULL),
  ('Assinar contrato de prestação de serviços', 'Jornada Comercial › Proposta & Fechamento', 'Relacionamento', 'comercial', '["Enviar contrato para assinatura","Confirmar assinatura","Arquivar contrato assinado"]', NULL),
  ('Enviar e-mail de boas-vindas com apresentação da equipe', 'Pré-Onboarding › Documentos necessários', 'Relacionamento', 'pre_ob', '["Preparar e-mail personalizado","Incluir foto da equipe","Apresentar metodologia resumida"]', NULL),
  ('Solicitar documentação da empresa', 'Pré-Onboarding › Documentos necessários', 'Relacionamento', 'pre_ob', '["CNPJ e contrato social","RG/CPF do sócio responsável","Comprovante de endereço","Certificado digital (se tiver)","Senha e-CAC (Receita Federal)"]', NULL),
  ('Verificar regime tributário', 'Pré-Onboarding › Documentos necessários', 'Estratégico', 'pre_ob', '["Simples Nacional?","Lucro Presumido?","Lucro Real?","Verificar pendências na Receita"]', NULL),
  ('Solicitar acesso ao internet banking', 'Pré-Onboarding › Acessos ao sistema financeiro', 'Relacionamento', 'pre_ob', '["Definir nível de acesso (consulta ou operacional)","Cadastrar IP se necessário","Testar acesso"]', NULL),
  ('Solicitar acesso ao ERP ou sistema de gestão', 'Pré-Onboarding › Acessos ao sistema financeiro', 'Implantação', 'pre_ob', '["Omie?","Conta Azul?","Meu Dinheiro Web?","Nibo?","Bom Controle?","Outro sistema?"]', NULL),
  ('Solicitar acesso à plataforma de emissão de NF', 'Pré-Onboarding › Acessos ao sistema financeiro', 'Implantação', 'pre_ob', '["Prefeitura (NFS-e)?","Dentro do ERP?","Testar emissão"]', NULL),
  ('Verificar maquininha e marketplaces', 'Pré-Onboarding › Acessos ao sistema financeiro', 'Relacionamento', 'pre_ob', '["Tem maquininha? Qual operadora?","Solicitar acesso ao painel","Tem marketplace? (Mercado Livre, etc)","Solicitar relatório de repasses"]', NULL),
  ('Definir canal principal de comunicação', 'Pré-Onboarding › Alinhamento de expectativas', 'Relacionamento', 'pre_ob', '["WhatsApp comercial?","E-mail?","Definir horário de atendimento"]', NULL),
  ('Confirmar agenda mensal', 'Pré-Onboarding › Alinhamento de expectativas', 'Relacionamento', 'pre_ob', '["Dia do fechamento","Dia da reunião mensal","Dia de emissão das NFs","Dia dos pagamentos"]', NULL),
  ('Definir responsável do cliente por área', 'Pré-Onboarding › Alinhamento de expectativas', 'Relacionamento', 'pre_ob', '["Responsável por NFs","Responsável por aprovações de pagamento","Responsável por documentos"]', NULL),
  ('Realizar reunião de kick-off', 'Onboarding › Kick-off Meeting', 'Relacionamento', 'onboarding', '["Enviar convite com pauta","Apresentar equipe responsável","Apresentar metodologia BPO","Alinhar escopo exato","Confirmar sistema financeiro","Definir calendário mensal","Registrar decisões da reunião"]', NULL),
  ('Apresentar sistema financeiro ao cliente', 'Onboarding › Kick-off Meeting', 'Implantação', 'onboarding', '["Mostrar como acessar","Mostrar onde ver relatórios","Mostrar como aprovar pagamentos","Tirar dúvidas"]', NULL),
  ('Mapear todas as contas bancárias', 'Onboarding › Diagnóstico financeiro inicial', 'Conciliação Bancária', 'onboarding', '["Listar todos os bancos","Confirmar agência e conta de cada um","Verificar saldo atual","Cadastrar no sistema"]', NULL),
  ('Levantar recebíveis e despesas fixas', 'Onboarding › Diagnóstico financeiro inicial', 'Fluxo de Caixa', 'onboarding', '["Listar clientes que pagam mensalmente","Listar despesas fixas (aluguel, folha, etc)","Identificar vencimentos","Lançar no sistema"]', NULL),
  ('Verificar inadimplentes em aberto', 'Onboarding › Diagnóstico financeiro inicial', 'Cobrança / Inadimplência', 'onboarding', '["Listar todos os devedores","Classificar por faixa de atraso","Definir estratégia de cobrança","Registrar no sistema"]', NULL),
  ('Entregar panorama financeiro inicial ao cliente', 'Onboarding › Diagnóstico financeiro inicial', 'Estratégico', 'onboarding', '["Montar resumo da situação atual","Identificar os 3 principais problemas","Apresentar ao cliente"]', NULL),
  ('Configurar plano de contas no ERP', 'Onboarding › Configuração no sistema', 'Implantação', 'onboarding', '["Definir categorias de CP","Definir categorias de CR","Criar centros de custo se necessário","Validar com o cliente"]', NULL),
  ('Cadastrar contas bancárias no sistema', 'Onboarding › Configuração no sistema', 'Implantação', 'onboarding', '["Cadastrar todas as contas","Conectar via OFX se possível","Lançar saldo inicial","Testar importação de extrato"]', NULL),
  ('Registrar todos os acessos no cadastro do cliente', 'Onboarding › Configuração no sistema', 'Implantação', 'onboarding', '["Internet banking","ERP/sistema","Plataforma de NF","Maquininha","Outros acessos relevantes"]', NULL),
  ('Configurar empresa no Omie ERP', 'Implantação › Configuração do software', 'Implantação', 'implantacao', '["Criar conta / acessar empresa","Configurar CNPJ e regime tributário","Cadastrar contas bancárias com OFX","Configurar plano de contas","Cadastrar fornecedores recorrentes","Ativar módulo de NF-e / NFS-e","Testar emissão de primeira NF"]', 'Omie'),
  ('Configurar empresa no Conta Azul', 'Implantação › Configuração do software', 'Implantação', 'implantacao', '["Criar conta / acessar empresa","Conectar via Open Finance","Configurar plano de contas","Cadastrar produtos/serviços","Configurar integrações (maquininha)","Testar boleto e NF"]', 'Conta Azul'),
  ('Configurar empresa no Meu Dinheiro Web', 'Implantação › Configuração do software', 'Implantação', 'implantacao', '["Acessar empresa","Cadastrar contas bancárias","Definir categorias","Lançar saldo inicial"]', 'Meu Dinheiro Web'),
  ('Configurar empresa no Nibo', 'Implantação › Configuração do software', 'Implantação', 'implantacao', '["Acessar empresa","Conectar contas via OFX","Configurar plano de contas gerencial","Ativar módulo DRE","Testar importação de extrato"]', 'Nibo'),
  ('Configurar empresa no Bom Controle', 'Implantação › Configuração do software', 'Implantação', 'implantacao', '["Acessar empresa","Cadastrar contas bancárias","Definir categorias de CP e CR"]', 'Bom Controle'),
  ('Lançar saldo inicial de todas as contas bancárias', 'Implantação › Primeiros lançamentos', 'Conciliação Bancária', 'implantacao', '["Confirmar saldo com extrato","Lançar no sistema","Validar com o cliente"]', NULL),
  ('Importar ou lançar contas a pagar do mês', 'Implantação › Primeiros lançamentos', 'Contas a Pagar', 'implantacao', '["Listar todos os compromissos do mês","Lançar com data de vencimento","Verificar se há duplicatas"]', NULL),
  ('Importar ou lançar contas a receber do mês', 'Implantação › Primeiros lançamentos', 'Contas a Receber', 'implantacao', '["Listar todos os recebimentos previstos","Lançar com data prevista","Verificar inadimplentes"]', NULL),
  ('Conciliar primeiros extratos bancários', 'Implantação › Primeiros lançamentos', 'Conciliação Bancária', 'implantacao', '["Baixar extrato do banco","Importar no sistema","Conciliar lançamento por lançamento","Verificar diferenças"]', NULL),
  ('Validar todos os lançamentos com o cliente', 'Implantação › Primeiros lançamentos', 'Estratégico', 'implantacao', '["Agendar call de validação","Apresentar o que foi lançado","Ajustar conforme feedback"]', NULL),
  ('Testar fluxo completo de operação', 'Implantação › Go-live & Validação', 'Implantação', 'implantacao', '["Lançar → conciliar → gerar DRE","Testar aprovação de pagamento","Testar emissão de NF","Confirmar que todos os acessos funcionam"]', NULL),
  ('Aplicar pesquisa de satisfação pós-implantação', 'Implantação › Go-live & Validação', 'Relacionamento', 'implantacao', '["Enviar formulário de satisfação","Registrar nota recebida","Registrar feedback e melhorias"]', NULL),
  ('Conferência bancária matinal', 'Rotina Operacional › Rotina Diária', 'Conciliação Bancária', 'operacional', '["Acessar internet banking de cada cliente","Verificar saldo atual de todas as contas","Identificar movimentações não reconhecidas","Confirmar recebimentos do dia anterior"]', NULL),
  ('Verificar contas a pagar com vencimento hoje', 'Rotina Operacional › Rotina Diária', 'Contas a Pagar', 'operacional', '["Acessar lista de CP do dia","Verificar se há saldo disponível","Obter autorização do cliente para pagamentos acima do limite","Efetuar pagamentos autorizados","Salvar comprovantes","Baixar os títulos no sistema"]', NULL),
  ('Agendar pagamentos do próximo dia útil', 'Rotina Operacional › Rotina Diária', 'Pagamentos', 'operacional', '["Verificar vencimentos de amanhã","Confirmar disponibilidade de saldo","Agendar no internet banking","Comunicar cliente sobre agendamentos realizados"]', NULL),
  ('Verificar recebimentos previstos para hoje', 'Rotina Operacional › Rotina Diária', 'Contas a Receber', 'operacional', '["Verificar pagamentos confirmados no banco","Baixar os títulos recebidos no sistema","Comunicar cliente sobre recebimentos do dia","Cobrar os não recebidos"]', NULL),
  ('Checar NFs a emitir hoje', 'Rotina Operacional › Rotina Diária', 'Emissão de NF', 'operacional', '["Verificar contratos com recorrência","Confirmar dados com o cliente se necessário","Emitir NFs pendentes no portal","Enviar XML e PDF para os clientes","Registrar número da NF no controle"]', NULL),
  ('Responder mensagens e pendências do dia', 'Rotina Operacional › Rotina Diária', 'Relacionamento', 'operacional', '["Verificar WhatsApp e e-mail","Responder dúvidas dos clientes","Registrar pendências que não foram resolvidas","Atualizar status das tarefas afetadas"]', NULL),
  ('Conciliação de plataformas — cartão, boleto e PIX', 'Rotina Operacional › Rotina Semanal', 'Conciliação Bancária', 'operacional', '["Baixar relatório da maquininha","Baixar relatório de boletos","Conciliar com lançamentos no sistema","Verificar divergências"]', NULL),
  ('Agendamento bancário da semana', 'Rotina Operacional › Rotina Semanal', 'Pagamentos', 'operacional', '["Listar pagamentos a vencer nos próximos 7 dias","Separar por banco","Agendar no internet banking","Confirmar com o cliente os que precisam de aprovação"]', NULL),
  ('Verificar aprovações de pagamento pendentes', 'Rotina Operacional › Rotina Semanal', 'Pagamentos', 'operacional', '["Listar pagamentos aguardando aprovação","Enviar lembrete ao cliente","Registrar aprovações recebidas"]', NULL),
  ('Emissão de NFs de serviço recorrentes', 'Rotina Operacional › Rotina Semanal', 'Emissão de NF', 'operacional', '["Verificar contratos com emissão semanal","Emitir NFs","Enviar para destinatários"]', NULL),
  ('Conferir inadimplência da semana', 'Rotina Operacional › Rotina Semanal', 'Cobrança / Inadimplência', 'operacional', '["Listar títulos vencidos","Classificar por faixa de atraso","Enviar cobranças conforme régua"]', NULL),
  ('Cobrar extrato bancário e documentos do cliente', 'Rotina Operacional › Fechamento Mensal', 'Conciliação Bancária', 'operacional', '["Solicitar extrato de todas as contas","Solicitar faturas de cartão","Solicitar comprovantes de despesas físicas","Solicitar NFs de compras em falta","Definir prazo para entrega (máximo dia 5 do mês seguinte)"]', NULL),
  ('Emitir NFs dos contratos de serviço BPO do mês', 'Rotina Operacional › Fechamento Mensal', 'Emissão de NF', 'operacional', '["Verificar lista de contratos recorrentes","Confirmar valores com o contrato","Emitir NFS-e no portal da prefeitura","Enviar para os clientes por e-mail","Registrar número das NFs emitidas"]', NULL),
  ('Verificar e cobrar guias de tributos do mês', 'Rotina Operacional › Fechamento Mensal', 'Contas a Pagar', 'operacional', '["DAS (Simples Nacional) — verificar vencimento e valor","GPS (INSS) — se Lucro Presumido","DARF (IRPJ/CSLL/PIS/COFINS) — se Lucro Presumido","ISS municipal — verificar guia","Confirmar recolhimento com o contador/cliente","Arquivar comprovantes de pagamento"]', NULL),
  ('Conciliar extrato bancário conta a conta', 'Rotina Operacional › Fechamento Mensal', 'Conciliação Bancária', 'operacional', '["Conciliar conta corrente principal","Conciliar demais contas","Conciliar cartão corporativo","Verificar lançamentos duplicados","Verificar lançamentos não identificados"]', NULL),
  ('Conciliar plataformas digitais', 'Rotina Operacional › Fechamento Mensal', 'Conciliação Bancária', 'operacional', '["Conciliar boletos emitidos x recebidos","Conciliar PIX recebidos","Conciliar maquininha (crédito e débito)","Conciliar marketplaces (ML, Shopee, etc)","Verificar taxas descontadas pelas plataformas"]', NULL),
  ('Enviar comprovantes de pagamentos do mês ao cliente', 'Rotina Operacional › Fechamento Mensal', 'Contas a Pagar', 'operacional', '["Organizar comprovantes por data","Criar pasta por cliente e mês","Enviar por e-mail ou pasta compartilhada","Confirmar recebimento pelo cliente"]', NULL),
  ('Fechar período no ERP', 'Rotina Operacional › Fechamento Mensal', 'DRE / Relatórios', 'operacional', '["Verificar se todos os lançamentos estão corretos","Revisar categorias dos lançamentos","Fechar mês no sistema","Gerar backup dos dados"]', NULL),
  ('Gerar relatório gerencial do mês', 'Rotina Operacional › Fechamento Mensal', 'DRE / Relatórios', 'operacional', '["Gerar relatório de receitas e despesas no sistema","Calcular margens do período","Comparar com mês anterior","Revisar valores antes de enviar"]', NULL),
  ('Gerar Fluxo de Caixa projetado para o próximo mês', 'Rotina Operacional › Fechamento Mensal', 'Fluxo de Caixa', 'operacional', '["Projetar receitas do próximo mês","Projetar despesas fixas e variáveis","Incluir tributos a vencer","Identificar gap de caixa","Alertar cliente se houver risco de saldo negativo"]', NULL),
  ('Preparar e enviar relatório executivo ao cliente', 'Rotina Operacional › Fechamento Mensal', 'DRE / Relatórios', 'operacional', '["Montar resumo executivo (1 página)","Incluir resultado do mês","Incluir fluxo de caixa projetado","Incluir indicadores (margem, inadimplência, ticket médio)","Enviar ao cliente 24h antes da reunião"]', NULL),
  ('Realizar reunião mensal de resultados', 'Rotina Operacional › Fechamento Mensal', 'Estratégico', 'operacional', '["Abrir com resultado do mês em 2 minutos","Apresentar top 3 pontos de atenção","Apresentar posição de caixa atual","Apresentar projeção do próximo mês","Definir top 3 prioridades do próximo mês","Registrar ata e enviar em até 24h"]', NULL),
  ('Calcular indicadores financeiros do mês', 'BPO Estratégico › Análise & Indicadores', 'DRE / Relatórios', 'estrategico', '["Margem Bruta","Margem Líquida","Ponto de Equilíbrio","Ticket médio","Taxa de inadimplência","Comparar com mês anterior e meta"]', NULL),
  ('Identificar os 3 maiores vazamentos de caixa', 'BPO Estratégico › Análise & Indicadores', 'Estratégico', 'estrategico', '["Analisar top 10 despesas","Comparar com mês anterior","Identificar oportunidades de corte","Preparar recomendações"]', NULL),
  ('Enviar relatório ao cliente 24h antes da reunião', 'BPO Estratégico › Reunião de Decisão', 'Estratégico', 'estrategico', '["DRE do mês","Fluxo de caixa projetado","Indicadores","Análise dos vazamentos"]', NULL),
  ('Conduzir reunião estratégica mensal', 'BPO Estratégico › Reunião de Decisão', 'Estratégico', 'estrategico', '["Resultado do mês em 2 minutos","Top 3 vazamentos identificados","Posição de caixa atual","Projeção próximos 30 dias","Definir top 3 prioridades","Registrar plano de ação"]', NULL),
  ('Enviar ata da reunião ao cliente', 'BPO Estratégico › Reunião de Decisão', 'Estratégico', 'estrategico', '["Registrar decisões tomadas","Definir responsáveis e prazos","Enviar em até 24h após a reunião"]', NULL),
  ('Avaliar saúde financeira do cliente mensalmente', 'Acompanhamento & Retenção › Saúde do Cliente', 'Estratégico', 'acompanhamento', '["Verificar se inadimplência está controlada","Verificar se o caixa está positivo","Verificar se as tarefas estão em dia","Calcular health score do mês","Registrar no cadastro do cliente"]', NULL),
  ('Identificar sinais de risco de churn', 'Acompanhamento & Retenção › Saúde do Cliente', 'Estratégico', 'acompanhamento', '["Cliente reclamou de alguma entrega?","Houve atraso recorrente em tarefas?","O cliente está respondendo normalmente?","O MRR está ameaçado?","Acionar plano de retenção se necessário"]', NULL),
  ('Monitorar satisfação com as entregas do mês', 'Acompanhamento & Retenção › Saúde do Cliente', 'Relacionamento', 'acompanhamento', '["Houve alguma entrega atrasada?","O cliente ficou satisfeito com o relatório?","Alguma reclamação foi registrada?","Registrar feedback no sistema"]', NULL),
  ('Aplicar NPS trimestral ao cliente', 'Acompanhamento & Retenção › NPS & Renovação', 'Relacionamento', 'acompanhamento', '["Enviar formulário de NPS (0-10)","Registrar nota e comentários","Analisar resultado (promotor, neutro, detrator)","Criar plano de ação para notas abaixo de 7","Registrar no cadastro do cliente"]', NULL),
  ('Renovação contratual anual', 'Acompanhamento & Retenção › NPS & Renovação', 'Estratégico', 'acompanhamento', '["Verificar vencimento do contrato (30 dias antes)","Preparar proposta de renovação com reajuste","Enviar ao decisor","Negociar e ajustar escopo se necessário","Assinar aditivo ou novo contrato","Arquivar contrato renovado"]', NULL),
  ('Identificar oportunidades de expansão de serviços', 'Acompanhamento & Retenção › Upsell & Expansão de Escopo', 'Estratégico', 'acompanhamento', '["Tem demanda por emissão de NF que ainda não fazemos?","Tem pagamentos que o cliente ainda faz manualmente?","Tem necessidade de relatórios gerenciais extras?","Há oportunidade de gerir mais contas bancárias?","Documentar oportunidade e apresentar proposta"]', NULL),
  ('Apresentar proposta de expansão de escopo', 'Acompanhamento & Retenção › Upsell & Expansão de Escopo', 'Relacionamento', 'acompanhamento', '["Preparar proposta com novo escopo e preço","Apresentar os benefícios ao cliente","Negociar e ajustar","Assinar aditivo contratual","Comunicar equipe operacional sobre a expansão"]', NULL),
  ('Receber e registrar aviso de cancelamento', 'Encerramento de Contrato › Aviso Prévio & Planejamento', 'Relacionamento', 'encerramento', '["Registrar data do aviso","Verificar cláusula de aviso prévio no contrato (geralmente 30 dias)","Calcular data de encerramento dos serviços","Comunicar o gestor responsável","Iniciar protocolo de encerramento"]', NULL),
  ('Alinhar o processo de encerramento com o cliente', 'Encerramento de Contrato › Aviso Prévio & Planejamento', 'Relacionamento', 'encerramento', '["Confirmar data final dos serviços","Definir o que será entregue (histórico, relatórios, senhas)","Definir responsável do cliente para receber os materiais","Agendar reunião de passagem"]', NULL),
  ('Organizar e entregar histórico financeiro do cliente', 'Encerramento de Contrato › Entrega do Histórico', 'Estratégico', 'encerramento', '["Exportar todos os extratos do período","Exportar lançamentos do ERP (CSV ou Excel)","Exportar relatórios gerenciais do período","Organizar por mês em pasta compartilhada","Enviar link de acesso ao cliente"]', NULL),
  ('Realizar reunião de passagem de informações', 'Encerramento de Contrato › Entrega do Histórico', 'Relacionamento', 'encerramento', '["Apresentar onde está cada arquivo","Explicar metodologia utilizada","Responder dúvidas do cliente","Apresentar pendências em aberto (se houver)","Registrar ata da reunião"]', NULL),
  ('Entregar senhas e acessos ao cliente', 'Encerramento de Contrato › Entrega do Histórico', 'Implantação', 'encerramento', '["Identificar todas as senhas e acessos gerenciados","Entregar de forma segura (não por e-mail aberto)","Confirmar que o cliente conseguiu acessar","Remover usuários da Fluxe do ERP e bancos"]', NULL),
  ('Emitir NF final e cobrar saldo devedor', 'Encerramento de Contrato › Financeiro & Encerramento Formal', 'Emissão de NF', 'encerramento', '["Verificar se há mensalidades em aberto","Emitir NF referente ao mês proporcional (se aplicável)","Cobrar saldo devedor","Confirmar recebimento antes de encerrar os acessos"]', NULL),
  ('Revogar acessos da equipe Fluxe', 'Encerramento de Contrato › Financeiro & Encerramento Formal', 'Implantação', 'encerramento', '["Revogar acesso ao internet banking","Revogar acesso ao ERP do cliente","Revogar acesso ao portal de NF","Revogar acesso a plataformas (maquininha, marketplace)","Confirmar revogação de todos os acessos","Registrar no sistema"]', NULL),
  ('Encerrar cadastro do cliente no sistema', 'Encerramento de Contrato › Financeiro & Encerramento Formal', 'Implantação', 'encerramento', '["Alterar status do cliente para \"inativo\"","Registrar data de encerramento","Registrar motivo do cancelamento","Arquivar contrato e documentação","Enviar e-mail de despedida e agradecimento"]', NULL),
  ('Listar e classificar todos os títulos vencidos', 'Cobrança & Inadimplência › Identificação & Triagem', 'Cobrança / Inadimplência', NULL, '["1 a 7 dias de atraso","8 a 30 dias de atraso","31 a 60 dias de atraso","Acima de 60 dias","Ordenar por valor (maiores primeiro)"]', NULL),
  ('D+1: Lembrete amigável via WhatsApp', 'Cobrança & Inadimplência › Régua de Comunicação', 'Cobrança / Inadimplência', NULL, '["Enviar mensagem amigável com o boleto em anexo","Confirmar que a mensagem foi entregue","Registrar tentativa no sistema"]', NULL),
  ('D+5: Cobrança formal por escrito', 'Cobrança & Inadimplência › Régua de Comunicação', 'Cobrança / Inadimplência', NULL, '["Enviar mensagem formal por WhatsApp","Enviar e-mail com boleto atualizado (juros e multa)","Mencionar que o débito pode ser negativado","Registrar no sistema"]', NULL),
  ('D+10: Ligação telefônica ao responsável financeiro', 'Cobrança & Inadimplência › Régua de Comunicação', 'Cobrança / Inadimplência', NULL, '["Ligar para o responsável financeiro","Ligar para o sócio se o financeiro não responder","Entender o motivo do atraso","Oferecer parcelamento se necessário","Registrar resultado da ligação"]', NULL),
  ('D+15: Oferecer acordo de parcelamento formal', 'Cobrança & Inadimplência › Régua de Comunicação', 'Cobrança / Inadimplência', NULL, '["Propor parcelamento com entrada","Definir número de parcelas e datas","Emitir novos boletos com vencimentos acordados","Formalizar o acordo por e-mail","Registrar acordo no sistema"]', NULL),
  ('D+30: Escalar para o sócio proprietário', 'Cobrança & Inadimplência › Régua de Comunicação', 'Cobrança / Inadimplência', NULL, '["Enviar notificação extrajudicial por e-mail","Contatar o sócio diretamente","Informar que os serviços podem ser suspensos","Dar prazo de 5 dias úteis para quitação","Registrar comunicação e resposta"]', NULL),
  ('D+60+: Avaliar negativação ou encaminhamento jurídico', 'Cobrança & Inadimplência › Régua de Comunicação', 'Cobrança / Inadimplência', NULL, '["Avaliar valor da dívida vs custo do processo","Consultar o cliente (BPO) sobre a decisão","Negativar no SPC/Serasa se aprovado","Encaminhar para advogado se valor justificar","Registrar decisão no sistema","Encerrar prestação de serviços se aplicável"]', NULL),
  ('Registrar acordo e emitir novo boleto', 'Cobrança & Inadimplência › Negociação & Baixa', 'Cobrança / Inadimplência', NULL, '["Registrar condições do acordo","Emitir boleto com novo vencimento","Enviar ao cliente"]', NULL),
  ('Confirmar recebimento e dar baixa', 'Cobrança & Inadimplência › Negociação & Baixa', 'Cobrança / Inadimplência', NULL, '["Confirmar no banco","Dar baixa no título","Arquivar comprovante","Comunicar ao cliente do BPO"]', NULL)
) AS d(titulo, descricao, categoria, etapa, checklist, software)
ON CONFLICT (empresa_id, titulo, categoria) WHERE ativo = true DO NOTHING;
